### ISSUE TITLE
From my understanding, gic_plotting needs three inputs?

### ISSUE THREAD

**Issue by angelachenmo** [UBC-MDS/gic_calculator#17]
`gic_plotting(interests, term_lengths)` is what we have
I am thinking according to https://www.tangerine.ca/en/widget/saving/gic_calc
we need three input 
1.principal amt
2.interests
3term_lengths
to be able to graph the bar chart. Let me know if everyone has a different idea.

**Comment by AlysenTownsley** [comment]
No longer required.
