### ISSUE TITLE
GIC_difference.py should call the function with a consistent name 

### ISSUE THREAD

**Issue by angelachenmo** [UBC-MDS/gic_calculator#18]
` # Calculate interest for both periods
    interest_n1 = calculate_gic_interest(n1_year, principal, interest_rate)
    interest_n2 = calculate_gic_interest(n2_year, principal, interest_rate)`
    
By calculate_gic_interest did you mean interest_calc?
Please see interest_calc for input order too :)

Thanks!

**Comment by AlysenTownsley** [comment]
No longer required
