### ISSUE TITLE
Update requirement for ReadTheDocs

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/gic_calculator#40]
The requirement file for ReadTheDocs is outdated. We have to update it for hosting the document later

**Comment by AlysenTownsley** [comment]
Copy in the new code from Tiffany's file in the py-pkgs Github repo. (copied in below). 

# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - poetry install
      
# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
