### ISSUE TITLE
Create example for the package

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/gic_calculator#42]
- Create 1 example per 1 function
- With a narrative and good storyline

**Comment by AlysenTownsley** [comment]
Everyone to write their portions into the google doc.
Alysen to compile all into the example.ipynb file

**Comment by tonyshumlh** [comment]
Example draft: https://docs.google.com/document/d/1bA2UaI0zw_RIWShu_-yAawwnFbkY7_BOYslPYIuKYBk/edit
