### ISSUE TITLE
Peer Review Feedbacks

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/gic_calculator#58]
Below are the summaries of the feedbacks from previous Milestone:

- [X] 1. `gic_calculator.py` is empty. We should delete this file if we don't plan to use it..
- [X] 2. The documentation for `interest_calc` and `calculate_gic_difference` does not follow a consistent style. e.g. n1_year (int) & principal : int
- [X] 3. Some branch names are not meaningful (they should reflect the work being done on the branch).

Below are the summaries of the suggestions/problems from peer:

- [X] 1. Fix: Add test coverage badge
- [X] 2. Fix: Fix the version number of the package to match with the one in Github release
- [ ] 3. Function Enhancement: Pop up the chart when running `gic_plotting` in non-interactive interface
- [X] 4. Fix: Fix the docstring example in `gic_plotting`
- [ ] 5. Function Enhancement: Add a simple portfolio function to output the time period and interest rate necessary for the desired principal and interest
- [X] 6. Fix: It is better to explicit have a statement and URL for the ReadTheDocs documentation in the README apart from the Doc badge
- [X] 7.  Fix: Fix the CI_CD status
- [X] 8. Fix: Include a link in the example.ipynb to reference a relevant article or post explaining the concept of GIC interest.
- [ ] 9. Function Enhancement: Consider adding an option to allow the users to include multiple comparisions as they choose in `gic_plotting`
- [ ] 10. Function Enhancement: Consider making Altair plots interactive with hovering 
- [x] 11. Improve the test coverage of the package

**Comment by AlysenTownsley** [comment]
This issue represents the overall summary for feedback received from the graded Milestone 1, as well as from the Milestone 4 Peer Review. Each item will be addressed individually, and a summary will be provided below with a commit link for each fix (as required).

**Comment by AlysenTownsley** [comment]
1. gic_calculator.py is empty. We should delete this file if we don't plan to use it.

Fix: deleted as part of prior milestone, commit:

**Comment by AlysenTownsley** [comment]
2. The documentation for interest_calc and calculate_gic_difference does not follow a consistent style. e.g. n1_year (int) & principal : int

Fix: gic_difference function docstring was updated to remain consistent with the interest_calc and gic_plotting docstrings. Commit:

**Comment by AlysenTownsley** [comment]
3. Some branch names are not meaningful (they should reflect the work being done on the branch).

Fix: This was addressed verbally with teammates, and it was aligned that the following commit message structure will be used:

**Comment by AlysenTownsley** [comment]
1. Fix: Add test coverage badge

**Comment by AlysenTownsley** [comment]
2. Fix: Fix the version number of the package to match with the one in Github release

**Comment by AlysenTownsley** [comment]
3. Function Enhancement: Pop up the chart when running gic_plotting in non-interactive interface

**Comment by AlysenTownsley** [comment]
4. Fix: Fix the docstring example in gic_plotting

**Comment by AlysenTownsley** [comment]
5. Function Enhancement: Add a simple portfolio function to output the time period and interest rate necessary for the desired principal and interest

**Comment by AlysenTownsley** [comment]
6. Fix: It is better to explicit have a statement and URL for the ReadTheDocs documentation in the README apart from the Doc badge

**Comment by AlysenTownsley** [comment]
7. Fix: Fix the CI_CD status

**Comment by AlysenTownsley** [comment]
8. Fix: Include a link in the example.ipynb to reference a relevant article or post explaining the concept of GIC interest.

**Comment by AlysenTownsley** [comment]
9. Function Enhancement: Consider adding an option to allow the users to include multiple comparisions as they choose in gic_plotting

**Comment by AlysenTownsley** [comment]
10. Function Enhancement: Consider making Altair plots interactive with hovering

**Comment by tonyshumlh** [comment]
11. Fix: Add test coverage badge

Completed: commit: https://github.com/UBC-MDS/gic_calculator/commit/8c59584e6a01deaf069f0f72a19c8a737d1b2006
