### ISSUE TITLE
Choose a suitable license to the package and justify your choice

### ISSUE THREAD

**Issue by sungg888** [UBC-MDS/gic_calculator#67]
We need to discuss about which license to use for our project. Here are some information about licenses below, from this link: https://choosealicense.com/licenses/.

[GNU AGPLv3](https://choosealicense.com/licenses/agpl-3.0/)
Permissions of this strongest copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.

[GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/)
Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.

[GNU LGPLv3](https://choosealicense.com/licenses/lgpl-3.0/)
Permissions of this copyleft license are conditioned on making available complete source code of licensed works and modifications under the same license or the GNU GPLv3. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. However, a larger work using the licensed work through interfaces provided by the licensed work may be distributed under different terms and without source code for the larger work.

[Mozilla Public License 2.0](https://choosealicense.com/licenses/mpl-2.0/)
Permissions of this weak copyleft license are conditioned on making available source code of licensed files and modifications of those files under the same license (or in certain cases, one of the GNU licenses). Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. However, a larger work using the licensed work may be distributed under different terms and without source code for files added in the larger work.

[Apache License 2.0](https://choosealicense.com/licenses/apache-2.0/)
A permissive license whose main conditions require preservation of copyright and license notices. Contributors provide an express grant of patent rights. Licensed works, modifications, and larger works may be distributed under different terms and without source code.

[MIT License](https://choosealicense.com/licenses/mit/)
A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.

[Boost Software License 1.0](https://choosealicense.com/licenses/bsl-1.0/)
A simple permissive license only requiring preservation of copyright and license notices for source (and not binary) distribution. Licensed works, modifications, and larger works may be distributed under different terms and without source code

[The Unlicense](https://choosealicense.com/licenses/unlicense/)
A license with no conditions whatsoever which dedicates works to the public domain. Unlicensed works, modifications, and larger works may be distributed under different terms and without source code.

**Comment by tonyshumlh** [comment]
It seems to me that basic license (Apache, MIT, Boost Software) offer a minimum requirement (requiring preservation of copyright and license notices). But moderate license (Mozilla, GNU LGPL) would also require users/contributors to make available complete source code of licensed works, while offering a flexibility that larger work using the licensed work through interfaces may be distributed under different terms and without source code.

**Comment by sungg888** [comment]
In our case, MIT License or Apache License 2.0 could be a good fitting. They are permissive, encourage open collaboration, and are widely understood and accepted in both open source and commercial environments. If we prefer to ensure modifications remain open, the Mozilla Public License 2.0 requiring modifications to be open while allowing the larger work to remain proprietary. Overall, I think for our case, MIT License is enough and it is a good fit.

**Comment by AlysenTownsley** [comment]
Thank you for the summary of the licenses @sungg888. I agree with both of your comments above regarding the MIT license for code coverage. However, this will not provide coverage for written work (the vignette - example.ipynb). In order to cover written work we will need to also add one of the Creative Commons licenses. Here is a link to help select a license (https://chooser-beta.creativecommons.org/). 

Perhaps the CC 4 (https://creativecommons.org/licenses/by/4.0/legalcode.en) is a good choice, as it requires that reusers give credit to the creator. Also, it allows reusers to distribute, remix, adapt, and build upon the material in any medium or format, even for commercial purposes.

**Comment by tonyshumlh** [comment]
I agree with the MIT + CC license combination for our package. The MIT license grant users the freedom to utilize and modify our package without significant restrictions. 
As our tutorial is a kind of creative output, Creative Commons license allows us to decide how openly or protectively we want to share our work. These 2 license can balance the openness of the package while ensuring due credit for everyone involved.

**Comment by sungg888** [comment]
I agree with the MIT+ CC license.
